leftnav:
- identifier: ad15bd0f-1b21-ec5c-dfb5-611fc79312fe
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 431e2767-3465-1d34-4f7b-cf733ab42717
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 0acd6ce7-d709-6718-e674-9668199c70c8
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 6f901e31-279b-5d81-8393-2f972f3539c2
  name: Assignments
  pageRef: /pages/assignments
  weight: 40
- identifier: ad59b35b-169a-f645-49f3-b0cb40c47e80
  name: Projects
  pageRef: /pages/projects
  weight: 50
